# Generated by Django 3.2.8 on 2024-03-03 15:04

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(default=None, help_text='Numarul de inmatriculare', max_length=255, validators=[home.models.validate_plate_number])),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, help_text='Numele clientului', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, help_text='Numele soferului', max_length=255)),
                ('last_name', models.CharField(default=None, help_text='Prenumele soferului', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, help_text='Numele clientului', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, help_text='Valoarea facturata', max_digits=9)),
                ('currency', models.CharField(choices=[('RON', 'RON'), ('EUR', 'EUR')], help_text='Valuta de pe factura', max_length=3)),
                ('series', models.CharField(choices=[('VAL', 'VAL'), ('VIC', 'VIC'), ('VLX', 'VLX')], help_text='Seria facturii', max_length=3)),
                ('number', models.IntegerField(default=0, help_text='Numarul facturii')),
                ('category', models.CharField(choices=[('INCOMING', 'VENIT'), ('OUTCOMING', 'CHELTUIALA')], help_text='Tipul facturii', max_length=10)),
                ('description', models.CharField(blank=True, default=None, help_text='Descriere optionala(ex: cursa BH - IF / revizie placute)', max_length=255, null=True)),
                ('cars', models.ManyToManyField(help_text='Masina / masinile pe care s-a facturat', to='home.Car')),
                ('client', models.ForeignKey(blank=True, default=None, help_text='Clientul de pe factura', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.client')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='drivers',
            field=models.ManyToManyField(help_text='Soferul / soferii de pe masina', to='home.Driver'),
        ),
    ]
