# Generated by Django 3.2.8 on 2024-03-03 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20240303_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='emit_date',
            field=models.DateTimeField(default=None, help_text='Data emitere factura', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('EMISA', 'EMISA'), ('INCASATA', 'INCASATA'), ('DEPASITA', 'DEPASITA')], default=None, help_text='Statusul facturii', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoicecar',
            name='expense_category',
            field=models.ForeignKey(blank=True, default=None, help_text='Categoria cheltuielii, NULL inseamna ca e venit', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.expensecategory'),
        ),
    ]
