# Generated by Django 3.2.8 on 2024-03-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20240303_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, help_text='Numele valutei', max_length=255)),
                ('value', models.DecimalField(decimal_places=4, default=0.0, help_text='Valoarea valutei', max_digits=9)),
                ('date', models.DateTimeField(auto_now=True, help_text='Data cursului')),
            ],
        ),
    ]
