# Generated by Django 3.2.8 on 2024-03-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='category',
            field=models.CharField(choices=[('INCOMING', 'VENIT'), ('OUTGOING', 'CHELTUIALA')], help_text='Tipul facturii', max_length=10),
        ),
    ]
