# Generated by Django 3.2.8 on 2024-03-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_invoice_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='category',
            field=models.CharField(choices=[('incoming', 'Venit'), ('outgoing', 'Cheltuială')], help_text='Tipul facturii', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('ron', 'RON'), ('eur', 'EUR')], help_text='Valuta de pe factura', max_length=3),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='series',
            field=models.CharField(choices=[('val', 'VAL'), ('vic', 'VIC'), ('vlx', 'VLX')], help_text='Seria facturii', max_length=3),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('issued', 'Emisă'), ('collected', 'Încasată'), ('paid', 'Plătită'), ('exceed', 'Depăsită')], default=None, help_text='Statusul facturii', max_length=10, null=True),
        ),
    ]
