# Generated by Django 3.2.8 on 2024-03-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20240317_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=None, help_text='Data scadentă factura', null=True),
        ),
    ]
